// import './globals.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import HeaderPage from "./components/header";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Head>
        <title>Digimap University</title>
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Logo_Hust.png/1200px-Logo_Hust.png"
        ></link>
        <meta
          name="description"
          content="This is a desription for My Next App"
        />
      </Head>
      <body className={inter.className} style={{ margin: 0 }}>
        <HeaderPage />
        <div style={{ display: "flex" }}>
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
